[project]
name = "estudopython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "attrs==23.2.0",
    "automat==22.10.0",
    "babel==2.10.3",
    "bcrypt==3.2.2",
    "blinker==1.7.0",
    "certifi==2023.11.17",
    "cfgv==3.4.0",
    "chardet==5.2.0",
    "click==8.1.6",
    "colorama==0.4.6",
    "configobj==5.0.8",
    "constantly==23.10.4",
    "cryptography==41.0.7",
    "distlib==0.3.8",
    "distro==1.9.0",
    "filelock==3.13.1",
    "httplib2==0.20.4",
    "hyperlink==21.0.0",
    "identify==2.5.35",
    "idna==3.6",
    "incremental==22.10.0",
    "jinja2==3.1.2",
    "jsonpatch==1.32",
    "jsonpointer==2.0",
    "jsonschema==4.10.3",
    "markdown-it-py==3.0.0",
    "markupsafe==2.1.5",
    "mdurl==0.1.2",
    "nodeenv==0.13.4",
    "oauthlib==3.2.2",
    "platformdirs==4.2.0",
    "pre-commit==3.6.2",
    "pyasn1==0.4.8",
    "pyasn1-modules==0.2.8",
    "pygments==2.17.2",
    "pyhamcrest==2.1.0",
    "pyjwt==2.7.0",
    "pyopenssl==23.2.0",
    "pyparsing==3.1.1",
    "pyrsistent==0.20.0",
    "pyserial==3.5",
    "pytz==2024.1",
    "pyyaml==6.0.1",
    "requests==2.31.0",
    "rich==13.7.1",
    "service-identity==24.1.0",
    "setuptools==68.1.2",
    "six==1.16.0",
    "twisted==24.3.0",
    "typing-extensions==4.10.0",
    "urllib3==2.0.7",
    "wheel==0.42.0",
    "zope-interface==6.1",
]
